---
# tasks file for ansible-role-mgmt-vpc

- name: Print current dir
  debug:
    msg: "Current dir {{ playbook_dir }}, role: {{ role_path }}"

- name: Create key pair for mgmt instances
  ec2_key:
    name: "{{ mgmt_key_pair }}"
    key_material: "{{ item }}"
    region: "{{ region }}"
  with_file: "{{ mgmt_key_path }}"

- name: Launch mgmt vpc creation
  cloudformation:
    stack_name: "{{ vpc_stack_name }}"
    state: present
    region: "{{ region }}"
    disable_rollback: false
    template: "{{ role_path }}/templates/create_mgmt_vpc.yml"
    template_parameters:
      MainCidrBlock: "{{ main_cidr_block }}"
      VpnCidrBlock: "{{ vpn_cidr_block }}"
      NatCidrBlock: "{{ nat_cidr_block }}"
      ToolingCidrBlock: "{{ tooling_cidr_block }}"
      AvailabilityZone: "{{ availability_zone }}"
      NatInstanceType: "{{ nat_instance_type }}"
      MgmtKeyPairName: "{{ mgmt_key_pair }}"
    tags:
      Name: Management VPC Stack

- block:
  - name: Launch dev tools creation
    cloudformation:
      stack_name: dev-tools
      state: present
      region: "{{ region }}"
      disable_rollback: false
      template: "{{ role_path }}/templates/create_atlassian_tools.yml"
      template_parameters:
        MgmtVpcStackName: "{{ vpc_stack_name }}"
        MgmtKeyPairName: "{{ mgmt_key_pair }}"
        BamboInstanceType: "{{ bamboo_instance_type }}"
        JiraInstanceType: "{{ jira_instance_type }}"
        BitbucketInstanceType: "{{ bitbucket_instance_type }}"
  when: install_atlassian